# 项目相关配置
epmc:
  # 名称
  name: 梧州学院疫情管理平台
  # 版本
  version: 1.1.0
  # 版权年份
  copyrightYear: 2020
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/epmc/uploadPath，Linux配置 /home/epmc/uploadPath）
  #profile: D:/epmc/uploadPath
  profile: /Users/mac/uploadPath
  # 获取ip地址开关
  addressEnabled: true

# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 88
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30
 
# 日志配置
logging:
  level:
    edu.gxuwz: info
    org.springframework: warn

# 用户配置
user:
  password:
    # 密码错误{maxRetryCount}次锁定10分钟
    maxRetryCount: 20

# Spring配置
spring:
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  # 资源信息
  messages:
    # 国际化资源文件路径
    basename: static/i18n/messages
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles: 
    active: druid
  # 文件上传
  servlet:
     multipart:
       # 单个文件大小
       max-file-size:  10MB
       # 设置总上传的文件大小
       max-request-size:  20MB
  # 服务模块
  devtools:
    restart:
      # 热部署开关
      enabled: true
  activemq:
    broker-url: tcp://localhost:61616
    #true 表示使用内置的MQ，false则连接服务器
    in-memory: true
    user: admin
    password: admin
    #true表示使用连接池；false时，每发送一条数据创建一个连接
    pool:
      enabled: true
      #连接池最大连接数
      max-connections: 30
      #空闲的连接过期时间，默认为30秒
      idle-timeout: 30000
      #强制的连接过期时间，
      #与idleTimeout的区别在于：idleTimeout是在连接空闲一段时间失效，
      #而expiryTimeout不管当前连接的情况，只要达到指定时间就失效。默认为0，never
      #expiry-timeout: 0
  mail:
    # QQ邮箱服务器
    host: smtp.qq.com
    # 邮箱用户
    username: 429829320@qq.com
    # QQ邮箱第三方授权码
    password: lftfzpcbwpoacajf
    # 编码类型
    default-encoding: UTF-8

# MyBatis
mybatis:
    # 搜索指定包别名
    typeAliasesPackage: edu.gxuwz.project.**.domain
    # 配置mapper的扫描，找到所有的mapper.xml映射文件
    mapperLocations: classpath:mybatis/**/*Mapper.xml
    # 加载全局的配置文件
    configLocation: classpath:mybatis/mybatis-config.xml

# PageHelper分页插件
pagehelper: 
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 

# Shiro
shiro:
  user:
    # 登录地址
    loginUrl: /login
    # 权限认证失败地址
    unauthorizedUrl: /unauth
    # 首页地址
    indexUrl: /index
    # 验证码开关
    captchaEnabled: true
    # 验证码类型 math 数组计算 char 字符
    captchaType: math
  cookie:
    # 设置Cookie的域名 默认空，即当前访问的域名
    domain: 
    # 设置cookie的有效访问路径
    path: /
    # 设置HttpOnly属性
    httpOnly: true
    # 设置Cookie的过期时间，天为单位
    maxAge: 30
  session:
    # Session超时时间，-1代表永不过期（默认30分钟）
    expireTime: 30
    # 同步session到数据库的周期（默认1分钟）
    dbSyncPeriod: 1
    # 相隔多久检查一次session的有效性，默认就是10分钟
    validationInterval: 10
    # 同一个用户最大会话数，比如2的意思是同一个账号允许最多同时两个人登录（默认-1不限制）
    maxSession: -1
    # 踢出之前登录的/之后登录的用户，默认踢出之前登录的用户
    kickoutAfter: false

# 防止XSS攻击
xss: 
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

# 代码生成
gen: 
  # 作者
  author: epmc
  # 默认生成包路径 system 需改成自己的模块名称 如 system monitor tool
  packageName: edu.gxuwz.project.system
  # 自动去除表前缀，默认是true
  autoRemovePre: true
  # 表前缀（生成类名不会包含表前缀，多个用逗号分隔）
  tablePrefix: sys_